services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab-results-ingest-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/hl7_db?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: phpmyadmin
      SPRING_DATASOURCE_PASSWORD: yataPassword@123
      SERVER_PORT: 8089
      SPACE_KEY: ${SPACE_KEY:-}
      SPACE_SECRET: ${SPACE_SECRET:-}
      SPACE_ENDPOINT: ${SPACE_ENDPOINT:-https://fra1.digitaloceanspaces.com}
      SPACE_REGION: ${SPACE_REGION:-us-east-1}
      SPACE_BUCKET: ${SPACE_BUCKET:-yata-medias}
    ports:
      - "11001:8089"
